-- Ensure each muscle group has 50 global exercises.
-- Safe to re-run: skips names that already exist.

insert into public.exercises (name, muscle_group, equipment, instructions)
select * from (values
  -- ===================== CHEST (50) =====================
  ('Bench Press', 'Chest', 'Barbell', 'Lie on bench, lower bar to chest, press up to lockout.'),
  ('Incline Bench Press', 'Chest', 'Barbell', 'Press bar from upper chest on an incline bench.'),
  ('Decline Bench Press', 'Chest', 'Barbell', 'Press bar from lower chest on a decline bench.'),
  ('Flat Dumbbell Press', 'Chest', 'Dumbbell', 'Press dumbbells from chest to lockout on a flat bench.'),
  ('Incline Dumbbell Press', 'Chest', 'Dumbbell', 'Press dumbbells up on an inclined bench.'),
  ('Decline Dumbbell Press', 'Chest', 'Dumbbell', 'Press dumbbells from lower chest on a decline bench.'),
  ('Cable Chest Fly', 'Chest', 'Cable', 'Bring handles together in front of chest with slight elbow bend.'),
  ('Incline Cable Fly', 'Chest', 'Cable', 'Cable fly from a low-to-high path targeting upper chest.'),
  ('Decline Cable Fly', 'Chest', 'Cable', 'Cable fly from a high-to-low path targeting lower chest.'),
  ('Pec Deck Fly', 'Chest', 'Machine', 'Bring arms together in an arc, squeeze chest at the middle.'),
  ('Machine Chest Press', 'Chest', 'Machine', 'Press handles forward to lockout, control the return.'),
  ('Incline Machine Press', 'Chest', 'Machine', 'Machine press on an incline path for upper chest.'),
  ('Push-Up', 'Chest', 'Bodyweight', 'Lower chest toward floor, press up while keeping body straight.'),
  ('Incline Push-Up', 'Chest', 'Bodyweight', 'Hands elevated push-up focusing upper chest and control.'),
  ('Decline Push-Up', 'Chest', 'Bodyweight', 'Feet elevated push-up for greater chest loading.'),
  ('Diamond Push-Up', 'Chest', 'Bodyweight', 'Hands close together under chest, emphasize triceps and inner chest.'),
  ('Wide-Grip Push-Up', 'Chest', 'Bodyweight', 'Hands placed wide to emphasize outer chest.'),
  ('Chest Dips', 'Chest', 'Bodyweight', 'Lean slightly forward on parallel bars, lower and press up.'),
  ('Smith Machine Bench Press', 'Chest', 'Machine', 'Bench press on a Smith machine for guided path.'),
  ('Smith Machine Incline Press', 'Chest', 'Machine', 'Incline press on a Smith machine.'),
  ('Landmine Press', 'Chest', 'Barbell', 'Press the free end of a landmine bar up and forward.'),
  ('Single-Arm Landmine Press', 'Chest', 'Barbell', 'One-arm landmine press for unilateral chest work.'),
  ('Svend Press', 'Chest', 'Plate', 'Squeeze a plate between palms and press forward.'),
  ('Floor Press', 'Chest', 'Barbell', 'Press from the floor to limit range and protect shoulders.'),
  ('Dumbbell Floor Press', 'Chest', 'Dumbbell', 'Press dumbbells from the floor with controlled lockout.'),
  ('Neutral-Grip Dumbbell Press', 'Chest', 'Dumbbell', 'Press with palms facing each other for shoulder comfort.'),
  ('Squeeze Press', 'Chest', 'Dumbbell', 'Press dumbbells while keeping them pressed together.'),
  ('Plate Press', 'Chest', 'Plate', 'Press weight plates together and extend arms forward.'),
  ('Guillotine Press', 'Chest', 'Barbell', 'Bench press to upper chest with wider grip and caution.'),
  ('Close-Grip Dumbbell Press', 'Chest', 'Dumbbell', 'Press with hands closer to emphasize inner chest.'),
  ('Cable Crossover', 'Chest', 'Cable', 'Cross cables in front of body and squeeze chest hard.'),
  ('Low Cable Crossover', 'Chest', 'Cable', 'Low-to-high crossover targeting upper chest.'),
  ('High Cable Crossover', 'Chest', 'Cable', 'High-to-low crossover targeting lower chest.'),
  ('Machine Fly', 'Chest', 'Machine', 'Seated machine fly through a fixed arc.'),
  ('Seated Cable Chest Press', 'Chest', 'Cable', 'Press cable handles forward from a seated position.'),
  ('Standing Cable Chest Press', 'Chest', 'Cable', 'Press cables forward while standing and bracing core.'),
  ('Ring Push-Up', 'Chest', 'Bodyweight', 'Push-up on gymnastic rings for instability and control.'),
  ('Archer Push-Up', 'Chest', 'Bodyweight', 'Shift load to one arm while the other stays extended.'),
  ('Plyometric Push-Up', 'Chest', 'Bodyweight', 'Explosive push-up with hands leaving the floor.'),
  ('Medicine Ball Push-Up', 'Chest', 'Other', 'Push-up with one or both hands on a medicine ball.'),
  ('Resistance Band Chest Press', 'Chest', 'Band', 'Press band handles forward from chest height.'),
  ('Resistance Band Chest Fly', 'Chest', 'Band', 'Open and close arms against band resistance.'),
  ('Kettlebell Floor Press', 'Chest', 'Kettlebell', 'Press kettlebells from the floor to lockout.'),
  ('Hex Press', 'Chest', 'Dumbbell', 'Press hex dumbbells while keeping them touching.'),
  ('Reverse Grip Bench Press', 'Chest', 'Barbell', 'Underhand grip bench press emphasizing upper chest.'),
  ('Paused Bench Press', 'Chest', 'Barbell', 'Pause the bar on the chest before pressing up.'),
  ('Tempo Bench Press', 'Chest', 'Barbell', 'Slow eccentric bench press for control and strength.'),
  ('Dumbbell Pullover', 'Chest', 'Dumbbell', 'Lower dumbbell overhead then pull back over chest.'),
  ('Machine Pullover', 'Chest', 'Machine', 'Pullover on a machine through a controlled arc.'),
  ('Isometric Chest Squeeze', 'Chest', 'Bodyweight', 'Press palms together hard and hold tension.'),

  -- ===================== BACK (50) =====================
  ('Deadlift', 'Back', 'Barbell', 'Hinge at hips, grip bar, drive through heels to stand tall.'),
  ('Pull-Up', 'Back', 'Bodyweight', 'Hang from bar, pull chin above bar, lower with control.'),
  ('Chin-Up', 'Back', 'Bodyweight', 'Underhand grip pull-up, chin over bar.'),
  ('Wide-Grip Pull-Up', 'Back', 'Bodyweight', 'Pull-up with hands wider than shoulders.'),
  ('Neutral-Grip Pull-Up', 'Back', 'Bodyweight', 'Pull-up with palms facing each other.'),
  ('Lat Pulldown', 'Back', 'Cable', 'Pull bar to upper chest, squeeze lats, control the return.'),
  ('Wide-Grip Lat Pulldown', 'Back', 'Cable', 'Wide grip pulldown emphasizing outer lats.'),
  ('Close-Grip Lat Pulldown', 'Back', 'Cable', 'Close grip pulldown for lower lats and arms.'),
  ('Reverse-Grip Lat Pulldown', 'Back', 'Cable', 'Underhand pulldown targeting lats and biceps.'),
  ('Barbell Row', 'Back', 'Barbell', 'Hinge forward, row bar to lower ribs.'),
  ('Pendlay Row', 'Back', 'Barbell', 'Strict bent-over row starting from the floor each rep.'),
  ('Yates Row', 'Back', 'Barbell', 'Underhand bent-over row with upright torso angle.'),
  ('Seated Cable Row', 'Back', 'Cable', 'Pull handle to torso, squeeze shoulder blades.'),
  ('Single-Arm Dumbbell Row', 'Back', 'Dumbbell', 'Row dumbbell to hip while braced on a bench.'),
  ('Chest-Supported Row', 'Back', 'Dumbbell', 'Lie face-down on incline bench and row dumbbells.'),
  ('T-Bar Row', 'Back', 'Barbell', 'Row the T-bar toward chest, keep torso braced.'),
  ('Meadows Row', 'Back', 'Barbell', 'Landmine single-arm row with staggered stance.'),
  ('Inverted Row', 'Back', 'Bodyweight', 'Hang under a bar, pull chest to bar.'),
  ('Face Pull', 'Back', 'Cable', 'Pull rope to face with high elbows.'),
  ('Straight-Arm Pulldown', 'Back', 'Cable', 'Keep arms nearly straight, pull bar down toward thighs.'),
  ('Good Morning', 'Back', 'Barbell', 'Hinge at hips with bar on back, keep spine neutral.'),
  ('Hyperextension', 'Back', 'Bodyweight', 'Raise torso on back-extension bench until hips are straight.'),
  ('Back Extension Machine', 'Back', 'Machine', 'Extend torso against machine resistance.'),
  ('Rack Pull', 'Back', 'Barbell', 'Partial deadlift from pins above the knee.'),
  ('Snatch-Grip Deadlift', 'Back', 'Barbell', 'Wide-grip deadlift for upper back and posterior chain.'),
  ('Sumo Deadlift High Pull', 'Back', 'Barbell', 'Sumo pull then shrug and pull bar high.'),
  ('Seal Row', 'Back', 'Barbell', 'Chest-supported row lying face-down on a raised bench.'),
  ('Machine Row', 'Back', 'Machine', 'Seated machine row with chest pad support.'),
  ('Iso-Lateral Row', 'Back', 'Machine', 'Unilateral machine row for each side independently.'),
  ('Cable Straight-Arm Pullover', 'Back', 'Cable', 'Pull cable from overhead toward hips with straight arms.'),
  ('Dumbbell Pullover for Lats', 'Back', 'Dumbbell', 'Pullover emphasizing lat stretch and contraction.'),
  ('Kroc Row', 'Back', 'Dumbbell', 'Heavy high-rep single-arm dumbbell row.'),
  ('Helms Row', 'Back', 'Dumbbell', 'Chest-supported row with elbows flared for mid-back.'),
  ('Band Pull-Apart', 'Back', 'Band', 'Pull band apart at shoulder height to train rear upper back.'),
  ('Resistance Band Row', 'Back', 'Band', 'Row band handles toward torso.'),
  ('TRX Row', 'Back', 'Bodyweight', 'Bodyweight row using suspension straps.'),
  ('Australian Pull-Up', 'Back', 'Bodyweight', 'Horizontal pull-up under a low bar.'),
  ('Weighted Pull-Up', 'Back', 'Bodyweight', 'Pull-up with added weight via belt or vest.'),
  ('Assisted Pull-Up', 'Back', 'Machine', 'Pull-up with machine assistance.'),
  ('One-Arm Lat Pulldown', 'Back', 'Cable', 'Single-arm pulldown for unilateral lat focus.'),
  ('Rope Lat Pulldown', 'Back', 'Cable', 'Pulldown using rope attachment and external rotation.'),
  ('Landmine Row', 'Back', 'Barbell', 'Two-hand or V-handle landmine row.'),
  ('Smith Machine Row', 'Back', 'Machine', 'Bent-over row on a Smith machine.'),
  ('Prone Y Raise', 'Back', 'Dumbbell', 'Raise arms into a Y while lying prone.'),
  ('Prone T Raise', 'Back', 'Dumbbell', 'Raise arms into a T while lying prone.'),
  ('Prone W Raise', 'Back', 'Dumbbell', 'Raise arms into a W while lying prone.'),
  ('Scapular Pull-Up', 'Back', 'Bodyweight', 'Hang and depress scapulae without bending elbows.'),
  ('Dead Hang', 'Back', 'Bodyweight', 'Hang from a bar to build grip and shoulder endurance.'),
  ('Farmer Carry', 'Back', 'Dumbbell', 'Walk while holding heavy weights at sides.'),
  ('Suitcase Carry', 'Back', 'Dumbbell', 'Walk while holding a weight on one side only.'),

  -- ===================== SHOULDERS (50) =====================
  ('Overhead Press', 'Shoulders', 'Barbell', 'Press bar from shoulders to overhead lockout.'),
  ('Dumbbell Shoulder Press', 'Shoulders', 'Dumbbell', 'Press dumbbells overhead from shoulder height.'),
  ('Seated Dumbbell Press', 'Shoulders', 'Dumbbell', 'Seated overhead press for stricter form.'),
  ('Arnold Press', 'Shoulders', 'Dumbbell', 'Rotate palms from facing you to forward while pressing up.'),
  ('Push Press', 'Shoulders', 'Barbell', 'Dip and drive with legs to help press bar overhead.'),
  ('Machine Shoulder Press', 'Shoulders', 'Machine', 'Press handles overhead to lockout.'),
  ('Smith Machine Shoulder Press', 'Shoulders', 'Machine', 'Overhead press on a guided Smith path.'),
  ('Lateral Raise', 'Shoulders', 'Dumbbell', 'Raise arms out to sides to shoulder height.'),
  ('Cable Lateral Raise', 'Shoulders', 'Cable', 'Raise cable handle out to the side.'),
  ('Machine Lateral Raise', 'Shoulders', 'Machine', 'Raise arms on a lateral raise machine.'),
  ('Front Raise', 'Shoulders', 'Dumbbell', 'Raise arms in front to shoulder height.'),
  ('Plate Front Raise', 'Shoulders', 'Plate', 'Raise a weight plate in front to eye level.'),
  ('Cable Front Raise', 'Shoulders', 'Cable', 'Raise cable handle forward to shoulder height.'),
  ('Rear Delt Fly', 'Shoulders', 'Dumbbell', 'Hinge forward and raise arms out to the sides.'),
  ('Cable Rear Delt Fly', 'Shoulders', 'Cable', 'Cross-body or dual-cable rear delt fly.'),
  ('Reverse Pec Deck', 'Shoulders', 'Machine', 'Face the pec deck and open arms backward.'),
  ('Upright Row', 'Shoulders', 'Barbell', 'Pull bar to chest height with elbows leading.'),
  ('Dumbbell Upright Row', 'Shoulders', 'Dumbbell', 'Upright row using dumbbells.'),
  ('Cable Upright Row', 'Shoulders', 'Cable', 'Upright row using a cable bar or rope.'),
  ('Shrugs', 'Shoulders', 'Dumbbell', 'Elevate shoulders toward ears, pause, lower.'),
  ('Barbell Shrugs', 'Shoulders', 'Barbell', 'Shrug with a barbell at the sides or front.'),
  ('Cable Shrugs', 'Shoulders', 'Cable', 'Shrug against cable resistance.'),
  ('Cuban Press', 'Shoulders', 'Dumbbell', 'External rotate then press for rotator cuff and delts.'),
  ('External Rotation', 'Shoulders', 'Cable', 'Rotate forearm outward against light cable resistance.'),
  ('Internal Rotation', 'Shoulders', 'Cable', 'Rotate forearm inward against light cable resistance.'),
  ('Face Pull to External Rotation', 'Shoulders', 'Cable', 'Face pull finishing with external rotation.'),
  ('Landmine Shoulder Press', 'Shoulders', 'Barbell', 'Single-arm landmine press for shoulders.'),
  ('Z Press', 'Shoulders', 'Barbell', 'Seated on floor overhead press with no back support.'),
  ('Dumbbell Z Press', 'Shoulders', 'Dumbbell', 'Floor-seated dumbbell overhead press.'),
  ('Bradford Press', 'Shoulders', 'Barbell', 'Alternate pressing bar in front of and behind head carefully.'),
  ('Behind-the-Neck Press', 'Shoulders', 'Barbell', 'Press from behind the neck with caution and mobility.'),
  ('Single-Arm Dumbbell Press', 'Shoulders', 'Dumbbell', 'One-arm overhead press for stability.'),
  ('Bottoms-Up Kettlebell Press', 'Shoulders', 'Kettlebell', 'Press kettlebell upside-down for stability demand.'),
  ('Kettlebell Overhead Press', 'Shoulders', 'Kettlebell', 'Press kettlebells overhead from rack position.'),
  ('Resistance Band Overhead Press', 'Shoulders', 'Band', 'Press band handles overhead.'),
  ('Resistance Band Lateral Raise', 'Shoulders', 'Band', 'Raise arms sideways against band tension.'),
  ('Resistance Band Face Pull', 'Shoulders', 'Band', 'Pull band toward face with high elbows.'),
  ('Pike Push-Up', 'Shoulders', 'Bodyweight', 'Push-up with hips high to load shoulders.'),
  ('Handstand Push-Up', 'Shoulders', 'Bodyweight', 'Press body upside-down against a wall.'),
  ('Wall Walk', 'Shoulders', 'Bodyweight', 'Walk feet up wall into handstand position.'),
  ('Y Raise', 'Shoulders', 'Dumbbell', 'Raise arms into a Y pattern for lower traps and delts.'),
  ('Scarecrow', 'Shoulders', 'Dumbbell', 'External rotate dumbbells at 90-degree elbows.'),
  ('Bus Driver', 'Shoulders', 'Plate', 'Hold a plate and rotate it like a steering wheel.'),
  ('Around the World', 'Shoulders', 'Dumbbell', 'Sweep light dumbbells in a wide arc around the body.'),
  ('Cable Y Raise', 'Shoulders', 'Cable', 'Raise cables into a Y overhead path.'),
  ('Seated Lateral Raise', 'Shoulders', 'Dumbbell', 'Strict lateral raises performed seated.'),
  ('Leaning Lateral Raise', 'Shoulders', 'Dumbbell', 'Lean away from support and raise the free arm.'),
  ('Partial Lateral Raise', 'Shoulders', 'Dumbbell', 'Short-range lateral raises for side delt overload.'),
  ('High Pull', 'Shoulders', 'Barbell', 'Explosive pull of the bar to upper chest.'),
  ('Snatch-Grip High Pull', 'Shoulders', 'Barbell', 'Wide-grip explosive high pull.'),

  -- ===================== ARMS (50) =====================
  ('Dumbbell Bicep Curl', 'Arms', 'Dumbbell', 'Curl dumbbells to shoulders, control the descent.'),
  ('Barbell Curl', 'Arms', 'Barbell', 'Curl bar to shoulders without swinging.'),
  ('EZ-Bar Curl', 'Arms', 'Barbell', 'Curl an EZ bar for wrist-friendly biceps work.'),
  ('Hammer Curl', 'Arms', 'Dumbbell', 'Curl with neutral grip, elbows tucked.'),
  ('Cross-Body Hammer Curl', 'Arms', 'Dumbbell', 'Curl dumbbell across the body toward opposite shoulder.'),
  ('Preacher Curl', 'Arms', 'Dumbbell', 'Curl on preacher bench for strict isolation.'),
  ('EZ-Bar Preacher Curl', 'Arms', 'Barbell', 'Preacher curl using an EZ bar.'),
  ('Concentration Curl', 'Arms', 'Dumbbell', 'Seated curl with elbow braced against inner thigh.'),
  ('Cable Bicep Curl', 'Arms', 'Cable', 'Curl cable handle to shoulders.'),
  ('Cable Rope Hammer Curl', 'Arms', 'Cable', 'Hammer curl using a rope attachment.'),
  ('Incline Dumbbell Curl', 'Arms', 'Dumbbell', 'Curl on an incline bench for long-head stretch.'),
  ('Spider Curl', 'Arms', 'Dumbbell', 'Curl while lying chest-down on incline bench.'),
  ('Drag Curl', 'Arms', 'Barbell', 'Drag bar up the torso by pulling elbows back.'),
  ('Reverse Curl', 'Arms', 'Barbell', 'Curl with overhand grip for brachialis and forearms.'),
  ('Cable Reverse Curl', 'Arms', 'Cable', 'Overhand cable curl for forearms and brachialis.'),
  ('Wrist Curl', 'Arms', 'Dumbbell', 'Curl wrists upward for forearm flexors.'),
  ('Reverse Wrist Curl', 'Arms', 'Dumbbell', 'Extend wrists upward for forearm extensors.'),
  ('Farmer Hold', 'Arms', 'Dumbbell', 'Hold heavy dumbbells at sides to build grip.'),
  ('Tricep Pushdown', 'Arms', 'Cable', 'Push cable attachment down, extend elbows fully.'),
  ('Rope Pushdown', 'Arms', 'Cable', 'Pushdown with rope, spread ends at the bottom.'),
  ('V-Bar Pushdown', 'Arms', 'Cable', 'Pushdown using a V-bar attachment.'),
  ('Skull Crusher', 'Arms', 'Barbell', 'Lower bar to forehead by bending elbows, extend up.'),
  ('Dumbbell Skull Crusher', 'Arms', 'Dumbbell', 'Lower dumbbells beside head then extend.'),
  ('Overhead Tricep Extension', 'Arms', 'Dumbbell', 'Extend dumbbell overhead by straightening elbows.'),
  ('Cable Overhead Extension', 'Arms', 'Cable', 'Overhead extension using a cable rope.'),
  ('Close-Grip Bench Press', 'Arms', 'Barbell', 'Bench press with hands closer than shoulder-width.'),
  ('JM Press', 'Arms', 'Barbell', 'Hybrid skull crusher and close-grip press.'),
  ('Tricep Kickback', 'Arms', 'Dumbbell', 'Extend forearm behind you while hinged forward.'),
  ('Cable Tricep Kickback', 'Arms', 'Cable', 'Kickback using a cable handle.'),
  ('Dips (Tricep Focus)', 'Arms', 'Bodyweight', 'Upright dips on parallel bars emphasizing triceps.'),
  ('Bench Dips', 'Arms', 'Bodyweight', 'Dip between benches with hands behind you.'),
  ('Diamond Push-Up Triceps', 'Arms', 'Bodyweight', 'Close-hand push-up emphasizing triceps.'),
  ('Tate Press', 'Arms', 'Dumbbell', 'Lower dumbbells to chest with elbows flared, then press.'),
  ('French Press', 'Arms', 'Barbell', 'Seated or lying overhead EZ-bar extension.'),
  ('Single-Arm Cable Curl', 'Arms', 'Cable', 'One-arm cable curl for even biceps development.'),
  ('Single-Arm Pushdown', 'Arms', 'Cable', 'One-arm tricep pushdown.'),
  ('Zottman Curl', 'Arms', 'Dumbbell', 'Curl up palms-up, rotate, lower palms-down.'),
  ('21s Bicep Curl', 'Arms', 'Barbell', 'Seven bottom, seven top, and seven full-range curls.'),
  ('Bayesian Curl', 'Arms', 'Cable', 'Cable curl with arm behind torso for stretch.'),
  ('Machine Bicep Curl', 'Arms', 'Machine', 'Curl on a plate-loaded or selectorized machine.'),
  ('Machine Tricep Extension', 'Arms', 'Machine', 'Extend elbows on a tricep machine.'),
  ('Band Bicep Curl', 'Arms', 'Band', 'Curl against band resistance.'),
  ('Band Tricep Pushdown', 'Arms', 'Band', 'Push band down by extending elbows.'),
  ('Kettlebell Curl', 'Arms', 'Kettlebell', 'Curl kettlebells with controlled tempo.'),
  ('Waiter Curl', 'Arms', 'Dumbbell', 'Curl a dumbbell held vertically like a tray.'),
  ('No-Money Curl', 'Arms', 'Band', 'Curl with external rotation against a band.'),
  ('Pronated Dumbbell Curl', 'Arms', 'Dumbbell', 'Curl while keeping palms facing down.'),
  ('Bodyweight Curl', 'Arms', 'Bodyweight', 'Curl using a low bar or rings under the body.'),
  ('Close-Grip Push-Up', 'Arms', 'Bodyweight', 'Push-up with hands under shoulders for triceps.'),
  ('Dead Hang Grip', 'Arms', 'Bodyweight', 'Hang from a bar to train grip and forearms.'),

  -- ===================== LEGS (50) =====================
  ('Barbell Back Squat', 'Legs', 'Barbell', 'Bar on upper back, squat until hips below knees.'),
  ('Front Squat', 'Legs', 'Barbell', 'Squat with bar racked on front of shoulders.'),
  ('Goblet Squat', 'Legs', 'Dumbbell', 'Hold dumbbell at chest and squat deep.'),
  ('Safety Bar Squat', 'Legs', 'Barbell', 'Squat using a safety squat bar.'),
  ('Box Squat', 'Legs', 'Barbell', 'Squat to a box, pause briefly, then stand.'),
  ('Pause Squat', 'Legs', 'Barbell', 'Pause in the bottom of the squat before standing.'),
  ('Bulgarian Split Squat', 'Legs', 'Dumbbell', 'Rear foot elevated split squat.'),
  ('Walking Lunge', 'Legs', 'Dumbbell', 'Step forward into lunges alternating legs.'),
  ('Reverse Lunge', 'Legs', 'Dumbbell', 'Step backward into a lunge and return.'),
  ('Lateral Lunge', 'Legs', 'Dumbbell', 'Step sideways into a lunge, keep other leg straight.'),
  ('Step-Up', 'Legs', 'Dumbbell', 'Step onto a box and drive through the front heel.'),
  ('Leg Press', 'Legs', 'Machine', 'Push platform away, control on the way back.'),
  ('Hack Squat', 'Legs', 'Machine', 'Squat on hack squat machine with controlled depth.'),
  ('Pendulum Squat', 'Legs', 'Machine', 'Machine squat on a pendulum path.'),
  ('Belt Squat', 'Legs', 'Machine', 'Squat with load hanging from a hip belt.'),
  ('Leg Extension', 'Legs', 'Machine', 'Extend knees against pad, squeeze quads at top.'),
  ('Single-Leg Extension', 'Legs', 'Machine', 'One-leg extension for unilateral quad work.'),
  ('Lying Leg Curl', 'Legs', 'Machine', 'Curl heels toward glutes on lying curl machine.'),
  ('Seated Leg Curl', 'Legs', 'Machine', 'Curl lower legs under seated pad.'),
  ('Nordic Hamstring Curl', 'Legs', 'Bodyweight', 'Lower torso forward while knees are fixed.'),
  ('Romanian Deadlift', 'Legs', 'Barbell', 'Hinge at hips with slight knee bend, feel hamstring stretch.'),
  ('Dumbbell Romanian Deadlift', 'Legs', 'Dumbbell', 'RDL using dumbbells at the sides.'),
  ('Stiff-Leg Deadlift', 'Legs', 'Barbell', 'Nearly straight-leg hinge emphasizing hamstrings.'),
  ('Sumo Deadlift', 'Legs', 'Barbell', 'Wide-stance deadlift emphasizing inner thighs.'),
  ('Trap Bar Deadlift', 'Legs', 'Barbell', 'Deadlift using a hex/trap bar.'),
  ('Calf Raise', 'Legs', 'Machine', 'Rise onto toes, pause, lower heels below platform.'),
  ('Seated Calf Raise', 'Legs', 'Machine', 'Press through balls of feet from seated position.'),
  ('Donkey Calf Raise', 'Legs', 'Machine', 'Calf raise with hips hinged and load on lower back.'),
  ('Single-Leg Calf Raise', 'Legs', 'Bodyweight', 'Calf raise on one leg for balance and strength.'),
  ('Sissy Squat', 'Legs', 'Bodyweight', 'Lean back while bending knees to load quads.'),
  ('Pistol Squat', 'Legs', 'Bodyweight', 'Single-leg squat to full depth with control.'),
  ('Shrimp Squat', 'Legs', 'Bodyweight', 'Single-leg squat holding the rear foot.'),
  ('Wall Sit', 'Legs', 'Bodyweight', 'Hold a seated position against a wall.'),
  ('Smith Machine Squat', 'Legs', 'Machine', 'Back squat on a Smith machine.'),
  ('Smith Machine Lunge', 'Legs', 'Machine', 'Split squat or lunge in a Smith machine.'),
  ('Cable Pull-Through Legs', 'Legs', 'Cable', 'Hinge and drive hips forward against cable.'),
  ('Cable Kickback Quad', 'Legs', 'Cable', 'Kick lower leg forward against cable for quads.'),
  ('Adductor Machine', 'Legs', 'Machine', 'Squeeze thighs together against machine pads.'),
  ('Abductor Machine', 'Legs', 'Machine', 'Open thighs against machine resistance.'),
  ('Copenhagen Plank Adductor', 'Legs', 'Bodyweight', 'Side plank with top leg supported for adductors.'),
  ('Jump Squat', 'Legs', 'Bodyweight', 'Explosive squat into a vertical jump.'),
  ('Broad Jump', 'Legs', 'Bodyweight', 'Jump forward for distance from an athletic stance.'),
  ('Box Jump', 'Legs', 'Other', 'Jump onto a box and stand tall.'),
  ('Kettlebell Swing Legs', 'Legs', 'Kettlebell', 'Hinge and snap hips to swing kettlebell.'),
  ('Goblet Lateral Squat', 'Legs', 'Dumbbell', 'Side-to-side squat holding a goblet weight.'),
  ('Heel-Elevated Squat', 'Legs', 'Dumbbell', 'Squat with heels raised to bias quads.'),
  ('Anderson Squat', 'Legs', 'Barbell', 'Squat starting from pins in the bottom position.'),
  ('Zercher Squat', 'Legs', 'Barbell', 'Squat with bar held in the crooks of the elbows.'),
  ('Overhead Squat', 'Legs', 'Barbell', 'Squat while holding a bar locked overhead.'),
  ('Cyclist Squat', 'Legs', 'Barbell', 'Narrow-stance heel-elevated squat for quads.'),

  -- ===================== GLUTES (50) =====================
  ('Hip Thrust', 'Glutes', 'Barbell', 'Drive hips up with upper back on bench, squeeze glutes.'),
  ('Smith Machine Hip Thrust', 'Glutes', 'Machine', 'Hip thrust using Smith bar for stability.'),
  ('Single-Leg Hip Thrust', 'Glutes', 'Bodyweight', 'Hip thrust on one leg for unilateral strength.'),
  ('Glute Bridge', 'Glutes', 'Bodyweight', 'Lie on back and lift hips by squeezing glutes.'),
  ('Weighted Glute Bridge', 'Glutes', 'Barbell', 'Glute bridge with a bar across the hips.'),
  ('Single-Leg Glute Bridge', 'Glutes', 'Bodyweight', 'Bridge with one foot planted and the other extended.'),
  ('Cable Glute Kickback', 'Glutes', 'Cable', 'Kick leg back against cable while braced.'),
  ('Machine Glute Kickback', 'Glutes', 'Machine', 'Kick back on a dedicated glute machine.'),
  ('Donkey Kick', 'Glutes', 'Bodyweight', 'On all fours, kick one heel toward ceiling.'),
  ('Fire Hydrant', 'Glutes', 'Bodyweight', 'On all fours, lift knee out to the side.'),
  ('Frog Pump', 'Glutes', 'Bodyweight', 'Lie on back with soles together, pulse hips up.'),
  ('Cable Pull-Through', 'Glutes', 'Cable', 'Hinge and pull cable between legs by driving hips forward.'),
  ('Romanian Deadlift Glutes', 'Glutes', 'Barbell', 'RDL emphasizing glute stretch and lockout.'),
  ('Sumo Romanian Deadlift', 'Glutes', 'Barbell', 'Wide-stance RDL for glutes and adductors.'),
  ('Bulgarian Split Squat Glute Focus', 'Glutes', 'Dumbbell', 'Longer stride split squat to bias glutes.'),
  ('Reverse Lunge Glute Focus', 'Glutes', 'Dumbbell', 'Long reverse lunge emphasizing rear-hip drive.'),
  ('Step-Up Glute Focus', 'Glutes', 'Dumbbell', 'High box step-up driving through the heel.'),
  ('Curtsy Lunge', 'Glutes', 'Dumbbell', 'Step one foot behind and across into a lunge.'),
  ('Lateral Band Walk', 'Glutes', 'Band', 'Side-step with a band around knees or ankles.'),
  ('Monster Walk', 'Glutes', 'Band', 'Forward or diagonal walk against band tension.'),
  ('Clamshell', 'Glutes', 'Band', 'Side-lying hip external rotation against a band.'),
  ('Side-Lying Hip Abduction', 'Glutes', 'Bodyweight', 'Lift top leg while lying on your side.'),
  ('Standing Hip Abduction', 'Glutes', 'Cable', 'Move working leg out to the side against cable.'),
  ('Standing Hip Extension', 'Glutes', 'Cable', 'Extend working leg behind you against cable.'),
  ('Hip Abductor Machine Glutes', 'Glutes', 'Machine', 'Open thighs against pads to train glute medius.'),
  ('45-Degree Hyperextension Glute', 'Glutes', 'Bodyweight', 'Back extension with rounded upper back to bias glutes.'),
  ('Reverse Hyperextension', 'Glutes', 'Machine', 'Raise legs behind you on a reverse hyper machine.'),
  ('Kettlebell Swing', 'Glutes', 'Kettlebell', 'Explosive hip hinge swing powered by glutes.'),
  ('American Swing', 'Glutes', 'Kettlebell', 'Swing kettlebell all the way overhead.'),
  ('Good Morning Glute Focus', 'Glutes', 'Barbell', 'Hip hinge good morning with glute emphasis.'),
  ('B-Stance Hip Thrust', 'Glutes', 'Barbell', 'Hip thrust with one foot slightly forward for bias.'),
  ('Feet-Elevated Glute Bridge', 'Glutes', 'Bodyweight', 'Bridge with feet on a bench for longer range.'),
  ('Marching Glute Bridge', 'Glutes', 'Bodyweight', 'Hold bridge and alternate lifting each foot.'),
  ('Banded Hip Thrust', 'Glutes', 'Band', 'Hip thrust with a band above the knees.'),
  ('Banded Glute Bridge', 'Glutes', 'Band', 'Bridge while pressing knees out against a band.'),
  ('Smith Machine Reverse Lunge', 'Glutes', 'Machine', 'Reverse lunge guided by a Smith machine.'),
  ('Cable Step-Back Lunge', 'Glutes', 'Cable', 'Step back into a lunge while holding a cable.'),
  ('Deficit Reverse Lunge', 'Glutes', 'Dumbbell', 'Reverse lunge from a small elevated surface.'),
  ('Sprinter Bridge', 'Glutes', 'Bodyweight', 'Single-leg bridge with non-working knee tucked.'),
  ('Quadruped Hip Extension', 'Glutes', 'Bodyweight', 'Extend one leg back from all-fours position.'),
  ('Bench Hip Thrust Hold', 'Glutes', 'Bodyweight', 'Hold the top of a hip thrust for time.'),
  ('Pulsing Hip Thrust', 'Glutes', 'Bodyweight', 'Short pulses at the top of a hip thrust.'),
  ('Glute Ham Raise', 'Glutes', 'Machine', 'Raise body using hamstrings and glutes on a GHD.'),
  ('Nordic Curl Glute Assist', 'Glutes', 'Bodyweight', 'Nordic curl with strong glute bracing.'),
  ('Kickstand RDL', 'Glutes', 'Dumbbell', 'RDL with rear foot lightly supporting.'),
  ('Single-Leg RDL', 'Glutes', 'Dumbbell', 'Hinge on one leg while reaching weight downward.'),
  ('Cable Hip Rotation', 'Glutes', 'Cable', 'Rotate the hip against cable resistance.'),
  ('Standing Glute Squeeze', 'Glutes', 'Bodyweight', 'Stand tall and squeeze glutes hard isometrically.'),
  ('Prone Hip Extension', 'Glutes', 'Bodyweight', 'Lie face-down and lift one or both legs.'),
  ('Swiss Ball Hip Extension', 'Glutes', 'Other', 'Bridge or extend hips with feet on a Swiss ball.'),

  -- ===================== CORE (50) =====================
  ('Plank', 'Core', 'Bodyweight', 'Hold straight-body position on forearms and toes.'),
  ('Side Plank', 'Core', 'Bodyweight', 'Hold body in a straight line on one forearm.'),
  ('Crunch', 'Core', 'Bodyweight', 'Curl shoulders off floor using abs, not neck.'),
  ('Sit-Up', 'Core', 'Bodyweight', 'Sit up from lying position with controlled tempo.'),
  ('Hanging Knee Raise', 'Core', 'Bodyweight', 'Hang from bar and raise knees toward chest.'),
  ('Hanging Leg Raise', 'Core', 'Bodyweight', 'Hang from bar and raise straight legs.'),
  ('Ab Wheel Rollout', 'Core', 'Other', 'Roll wheel forward while keeping core braced.'),
  ('Russian Twist', 'Core', 'Bodyweight', 'Rotate torso side to side while seated and leaning back.'),
  ('Dead Bug', 'Core', 'Bodyweight', 'Extend opposite arm and leg while keeping low back flat.'),
  ('Bird Dog', 'Core', 'Bodyweight', 'Extend opposite arm and leg from all-fours position.'),
  ('Cable Woodchop', 'Core', 'Cable', 'Rotate torso while pulling cable from high to low.'),
  ('Pallof Press', 'Core', 'Cable', 'Press cable handle forward and resist rotation.'),
  ('Mountain Climber', 'Core', 'Bodyweight', 'In plank, drive knees toward chest alternately.'),
  ('V-Up', 'Core', 'Bodyweight', 'Raise arms and legs together into a V shape.'),
  ('Toe Touch', 'Core', 'Bodyweight', 'Lie on back and reach hands toward toes.'),
  ('Bicycle Crunch', 'Core', 'Bodyweight', 'Alternate elbow-to-opposite-knee crunching pattern.'),
  ('Reverse Crunch', 'Core', 'Bodyweight', 'Curl hips off the floor toward the chest.'),
  ('Flutter Kick', 'Core', 'Bodyweight', 'Alternate small kicks while lying on your back.'),
  ('Scissor Kick', 'Core', 'Bodyweight', 'Cross extended legs over each other while lying down.'),
  ('Hollow Body Hold', 'Core', 'Bodyweight', 'Hold a hollow position with lower back pressed down.'),
  ('Hollow Body Rock', 'Core', 'Bodyweight', 'Rock gently while maintaining a hollow position.'),
  ('L-Sit', 'Core', 'Bodyweight', 'Support body on hands with legs extended forward.'),
  ('Dragon Flag', 'Core', 'Bodyweight', 'Lower and raise rigid body while holding a bench.'),
  ('Hanging Windshield Wiper', 'Core', 'Bodyweight', 'Hang and rotate straight legs side to side.'),
  ('Cable Crunch', 'Core', 'Cable', 'Kneel and crunch down against a cable rope.'),
  ('Machine Crunch', 'Core', 'Machine', 'Crunch on an abdominal machine.'),
  ('Decline Sit-Up', 'Core', 'Bodyweight', 'Sit-up on a decline bench.'),
  ('Decline Russian Twist', 'Core', 'Bodyweight', 'Twist on a decline bench for more challenge.'),
  ('Medicine Ball Slam', 'Core', 'Other', 'Slam a medicine ball into the floor explosively.'),
  ('Medicine Ball Rotational Throw', 'Core', 'Other', 'Rotate and throw a medicine ball against a wall.'),
  ('Standing Cable Crunch', 'Core', 'Cable', 'Crunch torso down while standing with a cable.'),
  ('Swiss Ball Crunch', 'Core', 'Other', 'Crunch while lying back over a Swiss ball.'),
  ('Swiss Ball Pike', 'Core', 'Other', 'From plank on ball, pike hips up.'),
  ('Swiss Ball Rollout', 'Core', 'Other', 'Roll a Swiss ball forward from the knees or feet.'),
  ('TRX Pike', 'Core', 'Bodyweight', 'Pike hips up with feet in suspension straps.'),
  ('TRX Mountain Climber', 'Core', 'Bodyweight', 'Mountain climbers with feet suspended.'),
  ('Deadlift Lockout Brace', 'Core', 'Barbell', 'Hold lockout and brace core hard under load.'),
  ('Suitcase Carry Core', 'Core', 'Dumbbell', 'Walk with one-sided load resisting side bend.'),
  ('Farmer Carry Core', 'Core', 'Dumbbell', 'Walk tall with heavy loads while bracing.'),
  ('Overhead Carry', 'Core', 'Dumbbell', 'Walk while holding a weight locked overhead.'),
  ('Copenhagen Plank', 'Core', 'Bodyweight', 'Side plank variation with top leg supported.'),
  ('Long-Lever Plank', 'Core', 'Bodyweight', 'Plank with hands farther forward for more demand.'),
  ('RKC Plank', 'Core', 'Bodyweight', 'High-tension plank with active full-body squeeze.'),
  ('Body Saw', 'Core', 'Bodyweight', 'Rock forward and back in a forearm plank.'),
  ('Stir the Pot', 'Core', 'Other', 'Plank on a Swiss ball and make small circles.'),
  ('Landmine Rotation', 'Core', 'Barbell', 'Rotate a landmine bar side to side.'),
  ('Half Kneeling Pallof Press', 'Core', 'Cable', 'Pallof press from a half-kneeling stance.'),
  ('Side Bend', 'Core', 'Dumbbell', 'Bend sideways with a dumbbell then return upright.'),
  ('Cable Side Bend', 'Core', 'Cable', 'Side bend against a cable handle.'),
  ('Toe-to-Bar', 'Core', 'Bodyweight', 'Hang and raise toes to touch the bar.'),

  -- ===================== CARDIO (50) =====================
  ('Running (treadmill)', 'Cardio', 'Machine', 'Steady-state or interval running.'),
  ('Outdoor Run', 'Cardio', 'Bodyweight', 'Run outdoors at an easy or interval pace.'),
  ('Sprint Intervals', 'Cardio', 'Bodyweight', 'Short maximal sprints with recovery walks.'),
  ('Cycling (stationary)', 'Cardio', 'Machine', 'Steady-state or interval cycling.'),
  ('Outdoor Cycling', 'Cardio', 'Other', 'Ride a bicycle outdoors for endurance.'),
  ('Assault Bike', 'Cardio', 'Machine', 'High-intensity air bike intervals.'),
  ('Rowing Machine', 'Cardio', 'Machine', 'Full-body rowing intervals or endurance.'),
  ('Elliptical', 'Cardio', 'Machine', 'Low-impact cardio on elliptical trainer.'),
  ('Stair Climber', 'Cardio', 'Machine', 'Climb stairs at a steady or interval pace.'),
  ('Stair Run', 'Cardio', 'Bodyweight', 'Run up stairs and walk or jog down.'),
  ('Jump Rope', 'Cardio', 'Other', 'Continuous or interval jump rope work.'),
  ('Double-Under', 'Cardio', 'Other', 'Jump rope with two rope passes per jump.'),
  ('Burpee', 'Cardio', 'Bodyweight', 'Squat, kick back to plank, return, and jump.'),
  ('Burpee Box Jump', 'Cardio', 'Other', 'Burpee followed by a jump onto a box.'),
  ('Battle Ropes', 'Cardio', 'Other', 'Alternate or double-arm rope waves.'),
  ('Jumping Jack', 'Cardio', 'Bodyweight', 'Jump feet out while raising arms overhead.'),
  ('High Knees', 'Cardio', 'Bodyweight', 'Run in place driving knees up quickly.'),
  ('Butt Kicks', 'Cardio', 'Bodyweight', 'Run in place kicking heels toward glutes.'),
  ('Skater Jump', 'Cardio', 'Bodyweight', 'Bound laterally from one foot to the other.'),
  ('Mountain Climber Cardio', 'Cardio', 'Bodyweight', 'Fast mountain climbers for heart rate.'),
  ('Shadow Boxing', 'Cardio', 'Bodyweight', 'Throw punches in the air with footwork.'),
  ('Heavy Bag Rounds', 'Cardio', 'Other', 'Strike a heavy bag in timed rounds.'),
  ('Swimming', 'Cardio', 'Bodyweight', 'Swim laps for aerobic conditioning.'),
  ('Rowing Intervals', 'Cardio', 'Machine', 'Hard rowing intervals with easy recovery.'),
  ('Treadmill Incline Walk', 'Cardio', 'Machine', 'Brisk walking on a steep treadmill incline.'),
  ('Power Walk', 'Cardio', 'Bodyweight', 'Fast outdoor walking with arm drive.'),
  ('Hiking', 'Cardio', 'Bodyweight', 'Walk over varied outdoor terrain.'),
  ('Rucking', 'Cardio', 'Other', 'Walk with a weighted backpack.'),
  ('Ski Erg', 'Cardio', 'Machine', 'Pull on a ski erg machine for cardio.'),
  ('Concept2 BikeErg', 'Cardio', 'Machine', 'Cardio intervals on a BikeErg.'),
  ('Spin Class Effort', 'Cardio', 'Machine', 'High-cadence interval cycling session.'),
  ('Tabata Bodyweight', 'Cardio', 'Bodyweight', '20 seconds work, 10 seconds rest circuits.'),
  ('EMOM Cardio', 'Cardio', 'Bodyweight', 'Every-minute-on-the-minute cardio stations.'),
  ('AMRAP Circuit', 'Cardio', 'Bodyweight', 'As many rounds as possible of a cardio circuit.'),
  ('Jumping Lunge', 'Cardio', 'Bodyweight', 'Alternate lunges with an explosive jump switch.'),
  ('Tuck Jump', 'Cardio', 'Bodyweight', 'Jump and tuck knees toward chest.'),
  ('Seal Jack', 'Cardio', 'Bodyweight', 'Jumping jack variation with arms swinging in front.'),
  ('Cross Jack', 'Cardio', 'Bodyweight', 'Jumping jack where feet and arms cross midline.'),
  ('Fast Feet', 'Cardio', 'Bodyweight', 'Rapid in-place foot taps for conditioning.'),
  ('Ladder Drills', 'Cardio', 'Other', 'Quick footwork through an agility ladder.'),
  ('Cone Shuttle Run', 'Cardio', 'Bodyweight', 'Sprint back and forth between cones.'),
  ('Beep Test Effort', 'Cardio', 'Bodyweight', 'Multi-stage shuttle run conditioning.'),
  ('Sled Push', 'Cardio', 'Other', 'Push a weighted sled over a set distance.'),
  ('Sled Pull', 'Cardio', 'Other', 'Pull a sled toward you or walk backward pulling.'),
  ('Farmer Carry Cardio', 'Cardio', 'Dumbbell', 'Continuous loaded carries for conditioning.'),
  ('Kettlebell Swing Cardio', 'Cardio', 'Kettlebell', 'High-rep swings for metabolic conditioning.'),
  ('Thruster Cardio', 'Cardio', 'Dumbbell', 'Front squat into overhead press for conditioning.'),
  ('Wall Ball', 'Cardio', 'Other', 'Squat and throw a medicine ball to a target.'),
  ('Row + Burpee Couple', 'Cardio', 'Machine', 'Alternate short rowing pieces with burpees.'),
  ('Dance Cardio', 'Cardio', 'Bodyweight', 'Continuous dance-based movement for heart rate.')
) as v(name, muscle_group, equipment, instructions)
where not exists (
  select 1 from public.exercises e where e.name = v.name and e.user_id is null
);
